name: Build AzulSCSI firmware

on: 
  push:
  workflow_dispatch:

jobs:
  build_firmware:
    name: Build firmware on Ubuntu 20.04
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
        with:
          path: AzulSCSI
          fetch-depth: "0"
      
      - name: Install platformio
        run: |
          sudo pip install platformio
      
      - name: Build firmware
        run: |
          cd AzulSCSI
          pio run -v
    
      - name: Rename firmware files
        run: |
          cd AzulSCSI
          utils/rename_binaries.sh

      - name: Upload binaries into build artifacts
        uses: actions/upload-artifact@v2
        with:
          path: AzulSCSI/distrib/*
          name: AzulSCSI binaries
      
      - name: Remove old binaries from release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
        run: |
          gh api repos/${GITHUB_REPOSITORY}/releases/tags/latest | jq -r '.assets[] | [.url] | @tsv' | xargs -n 1 gh api -X DELETE || true

      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
        run: |
          cd AzulSCSI
          git tag -d latest
          git tag latest
          git push origin --force latest
          cd distrib
          gh release upload --repo ${GITHUB_REPOSITORY} --clobber latest *

